[package]
name = "vxe"
version = "0.1.0"
authors = ["TheJebForge <jeb@thejebforge.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "*"
luminance = "*"
luminance-glfw = "*"
luminance-windowing = "*"